#!/bin/bash

get_title() {
    hyprctl activewindow -j | jq -r '.title | if . == "" then "Empty" else . end'
}

get_title

socat -u "UNIX-CONNECT:$XDG_RUNTIME_DIR/hypr/$HYPRLAND_INSTANCE_SIGNATURE/.socket2.sock" - | while read -r line; do
    case ${line%%>>*} in
        activewindow)
            get_title
            ;;
    esac
done
