# Autostart configuration
# Autostart necessary processes (like notifications daemons, status bars, etc.)

exec-once = eww daemon && eww open bar0 && eww open bar1
exec-once = mako
exec-once = hyprpaper
exec-once = hypridle

# Clipboard history (cliphist)
exec-once = wl-paste --type text --watch cliphist store
exec-once = wl-paste --type image --watch cliphist store

# exec-once = waybar & firefox
