# Window rules configuration
# See https://wiki.hypr.land/Configuring/Window-Rules/ for more

windowrule {
    # Ignore maximize requests from all apps. You'll probably like this.
    name = suppress-maximize-events
    match:class = .*

    suppress_event = maximize
}

windowrule {
    # Fix some dragging issues with XWayland
    name = fix-xwayland-drags
    match:class = ^$
    match:title = ^$
    match:xwayland = true
    match:float = true
    match:fullscreen = false
    match:pin = false

    no_focus = true
}

# Hyprland-run windowrule
windowrule {
    name = move-hyprland-run

    match:class = hyprland-run

    move = 20 monitor_h-120
    float = yes
}

# Eww bar window rules
windowrule {
    name = eww-bar0

    match:class = ^Eww$
    match:title = ^Eww - bar0$

    pin = true
    float = yes
    move = 0 0
    no_focus = true
}

windowrule {
    name = eww-bar1

    match:class = ^Eww$
    match:title = ^Eww - bar1$

    pin = true
    float = yes
    move = 1920 0
    no_focus = true
}



# Eww control panel window rules
windowrule {
    name = eww-control-panel0

    match:class = ^Eww$
    match:title = ^Eww - control_panel0$

    pin = true
    float = yes
    move = 908 40
    no_focus = true
}

windowrule {
    name = eww-control-panel1

    match:class = ^Eww$
    match:title = ^Eww - control_panel1$

    pin = true
    float = yes
    move = 2828 40
    no_focus = true
}
